1) array file(filename)							1)fclose(file_handle)
2) array explode(" ", string)						2)array_unshift(array, element)
3) string filetype(filename)						3)array_shift(array)
4) array stat(filename)							4)rsort(array)
5) boolean unlink(filename)						5)asort(array)
6) boolean copy(source, destination)					6)shuffle(array)
7) file_handle fopen(filename, mode)					7)extract(array)
8) int fwrite(filename, string)						8)ksort(array)
9) string implode("\n", array)						9)arsort(array)
10) array array(array_elements)						10)krsort(array)
11) int count(array)							11)include("filename")
12) array array_slice(array, start, end)
13) array array_chunk(array, each_array_size, key_preservation)
14) array array_filter(array, function_name)
15) array array_reverse(array)
16) array explode(",", string)
17) string strtolower(string)
18) string strtoupper(string)
19) string str_pad(string, new_size, "*", STR_PAD_BOTH)
20) string ltrim(string, " ")
21) string strrev(string)
22) string str_replace(existing_sepa, new_sepa, string)
23) int strrpos(string , " ")
24) int strpos(large_string, small_string)
25) int strncmp(string1, string2, n)
